In [1]:
2 + 3 + 9

14

In [2]:
99 - 73

26

In [3]:
23.54 * -1432

-33709.28

In [4]:
100 / 7

14.285714285714286

In [5]:
100 // 7

14

In [6]:
100 % 7

2

In [7]:
5 ** 3

125

In [8]:
((2 + 5) * (17 - 3)) / (4 ** 3)

1.53125

In [15]:
my_favorite_number = 1
my_least_favorite_number = 5
a_neutral_number = 3

In [16]:
# Equality check - True
my_favorite_number == 1

True

In [17]:
# Equality check - False
my_favorite_number == my_least_favorite_number

False

In [18]:
# Equality check - True
my_favorite_number != a_neutral_number

True

In [19]:
# Not equal check - False
a_neutral_number != 3

False

In [20]:
# Greater than check - True
my_least_favorite_number > a_neutral_number

True

**LATIHAN DATA PREPARATION**

In [21]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5],
                        [-1.5, 2.4, 3.5],
                        [0.5, -7.9, 5.6],
                        [5.9, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [22]:
sample_data.shape

(4, 3)

Teknik Binarisation

In [23]:
# parameter yg digunakan untuk ambang batas
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

Teknik Scalling

In [24]:
# scalling min max scaller
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessor.fit(sample_data)

# cara 1
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [25]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

Teknik Normalization L1

In [26]:
li_normalizer = preprocessing.Normalizer(norm='l1')
li_normalizer.fit(sample_data)
l1_normalized_data = li_normalizer.transform(sample_data)
l1_normalized_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

Teknik Normalization L2

In [27]:
li_normalized_data = preprocessing.Normalizer(norm='l2')
li_normalized_data.fit(sample_data)
l2_normalized_data = li_normalized_data.transform(sample_data)
l2_normalized_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])

Encoding

In [33]:
label_kategori_hari = ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu']
encoder = preprocessing.LabelEncoder()
encoder.fit(label_kategori_hari)

print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
  print(item, '-->', i)


Label mapping:
jumat --> 0
kamis --> 1
minggu --> 2
rabu --> 3
sabtu --> 4
selasa --> 5
senin --> 6
